only testcafe tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -68,13 +68,13 @@ jobs:
              ANOMALYIN=100 -e ANOMALYOUT=100 -e BACKEND=http://172.17.0.1:8000 \
              -e PORT=8001 --expose 8001 franbuehler/modsecurity-crs
 
-      - run:
-           name: Start OWASP ModSecurity CRS Container in front of API for ZAP Scan
-           #http://172.17.0.4:8003
-           command: |
-             docker run -dt --name apachecrsapi -e PARANOIA=1 -e \
-             ANOMALYIN=1 -e ANOMALYOUT=1 -e BACKEND=http://172.17.0.1:8090 \
-             -e PORT=8003 --expose 8003 franbuehler/modsecurity-crs
+#      - run:
+#           name: Start OWASP ModSecurity CRS Container in front of API for ZAP Scan
+#           #http://172.17.0.4:8003
+#           command: |
+#             docker run -dt --name apachecrsapi -e PARANOIA=1 -e \
+#             ANOMALYIN=1 -e ANOMALYOUT=1 -e BACKEND=http://172.17.0.1:8090 \
+#             -e PORT=8003 --expose 8003 franbuehler/modsecurity-crs
 
 #      - run:
 #           name: Start OWASP ModSecurity CRS Container in front of application for ZAP Active Scan
@@ -104,8 +104,8 @@ jobs:
             docker cp tmp.conf apachecrsmeantc:/etc/httpd/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf;
             docker exec apachecrsmeantc /usr/sbin/httpd -k graceful
             # CRS container for ZAP API Scan:
-            docker cp tmp.conf apachecrsapi:/etc/httpd/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf;
-            docker exec apachecrsapi /usr/sbin/httpd -k graceful
+#            docker cp tmp.conf apachecrsapi:/etc/httpd/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf;
+#            docker exec apachecrsapi /usr/sbin/httpd -k graceful
             # CRS container for ZAP Scan:
 #            docker cp tmp.conf apachecrsactive:/etc/httpd/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf;
 #            docker exec apachecrsactive /usr/sbin/httpd -k graceful
@@ -114,15 +114,15 @@ jobs:
 #            printf "\nSecRuleUpdateTargetById 942420 \"!REQUEST_COOKIES:session\"\n" > tmp.conf
 #            printf "\nSecRuleUpdateTargetById 942440 \"!REQUEST_COOKIES:session\"\n" > tmp.conf
 #
-      - run:
-          name: ZAP Baseline Scan of application (without CRS)
-          command: |
-             (
-             docker pull owasp/zap2docker-weekly && \
-             docker run -t owasp/zap2docker-weekly zap-baseline.py \
-                -t http://172.17.0.1:8000/ -l WARN || \
-              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-             )
+#      - run:
+#          name: ZAP Baseline Scan of application (without CRS)
+#          command: |
+#             (
+#             docker pull owasp/zap2docker-weekly && \
+#             docker run -t owasp/zap2docker-weekly zap-baseline.py \
+#                -t http://172.17.0.1:8000/ -l WARN || \
+#              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+#             )
 
 #      # https://hub.docker.com/r/ictu/zap2docker-weekly/
 #      # This Active Scan has to be developed: a custom config_file and context file
@@ -178,43 +178,43 @@ jobs:
 #             )
 #
       # A zap-api.conf could be developed
-      - run:
-          name: ZAP API scan of application (without CRS)
-          command: |
-             (
-             docker pull owasp/zap2docker-weekly && \
-             docker run -t owasp/zap2docker-weekly zap-api-scan.py \
-                -u https://raw.githubusercontent.com/franbuehler/pixi-crs/master/zap-api.conf?token=AQ6RVdBQnWmIHjOULcbaM-1untbAtqkkks5aoZmqwA \
-                -f openapi -l WARN \
-                -t http://172.17.0.1:8090/swagger.json \
-                -z "config formhandler.fields.field\(0\).fieldId=user" \
-                -z "config formhandler.fields.field\(0\).value=test@pixi.owasp" \
-                -z "config formhandler.fields.field\(0\).enabled=true" \
-                -z "config formhandler.fields.field\(1\).fieldId=pass" \
-                -z "config formhandler.fields.field\(1\).value=testpass" \
-                -z "config formhandler.fields.field\(1\).enabled=true" || \
-                # we know this is an insecure application:
-                exit 0
-              )
-
+#      - run:
+#          name: ZAP API scan of application (without CRS)
+#          command: |
+#             (
+#             docker pull owasp/zap2docker-weekly && \
+#             docker run -t owasp/zap2docker-weekly zap-api-scan.py \
+#                -u https://raw.githubusercontent.com/franbuehler/pixi-crs/master/zap-api.conf?token=AQ6RVdBQnWmIHjOULcbaM-1untbAtqkkks5aoZmqwA \
+#                -f openapi -l WARN \
+#                -t http://172.17.0.1:8090/swagger.json \
+#                -z "config formhandler.fields.field\(0\).fieldId=user" \
+#                -z "config formhandler.fields.field\(0\).value=test@pixi.owasp" \
+#                -z "config formhandler.fields.field\(0\).enabled=true" \
+#                -z "config formhandler.fields.field\(1\).fieldId=pass" \
+#                -z "config formhandler.fields.field\(1\).value=testpass" \
+#                -z "config formhandler.fields.field\(1\).enabled=true" || \
+#                # we know this is an insecure application:
+#                exit 0
+#              )
+#
       # A zap-api.conf could be developed
-      - run:
-          name: ZAP API scan of application with CRS
-          command: |
-             (
-             docker pull owasp/zap2docker-weekly && \
-             docker run -t owasp/zap2docker-weekly zap-api-scan.py \
-                -u https://raw.githubusercontent.com/franbuehler/pixi-crs/master/zap-api.conf?token=AQ6RVdBQnWmIHjOULcbaM-1untbAtqkkks5aoZmqwA \
-                -f openapi -l WARN \
-                -t http://172.17.0.4:8003/swagger.json \
-                -z "config formhandler.fields.field\(0\).fieldId=user" \
-                -z "config formhandler.fields.field\(0\).value=test@pixi.owasp" \
-                -z "config formhandler.fields.field\(0\).enabled=true" \
-                -z "config formhandler.fields.field\(1\).fieldId=pass" \
-                -z "config formhandler.fields.field\(1\).value=testpass" \
-                -z "config formhandler.fields.field\(1\).enabled=true" || \
-                if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-              )
+#      - run:
+#          name: ZAP API scan of application with CRS
+#          command: |
+#             (
+#             docker pull owasp/zap2docker-weekly && \
+#             docker run -t owasp/zap2docker-weekly zap-api-scan.py \
+#                -u https://raw.githubusercontent.com/franbuehler/pixi-crs/master/zap-api.conf?token=AQ6RVdBQnWmIHjOULcbaM-1untbAtqkkks5aoZmqwA \
+#                -f openapi -l WARN \
+#                -t http://172.17.0.4:8003/swagger.json \
+#                -z "config formhandler.fields.field\(0\).fieldId=user" \
+#                -z "config formhandler.fields.field\(0\).value=test@pixi.owasp" \
+#                -z "config formhandler.fields.field\(0\).enabled=true" \
+#                -z "config formhandler.fields.field\(1\).fieldId=pass" \
+#                -z "config formhandler.fields.field\(1\).value=testpass" \
+#                -z "config formhandler.fields.field\(1\).enabled=true" || \
+#                if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+#              )
 
       - run:
           name: Application Tests with Testcafe
@@ -264,13 +264,13 @@ jobs:
           # we always want to see this step:        
           when: always
 
-      - run:
-          name: Show ModSecurity logs of ZAP API Scan
-          command: |
-              docker exec apachecrsapi cat /etc/httpd/logs/error.log | grep -o -E " (at|against) .*\[file.*\[id \"[0-9]+.*\[msg \"[^\"]+" | tr -d \" | sed -e "s/ at the end of input at/ at/" -e "s/ required. /. /" -e "s/\[rev .*\[msg/[msg/" -e "s/\. / /" -e "s/(Total .*/(Total ...) .../" | tr -d \] | cut -d\  -f3,9,11- | sed -e "s/^\([^ ]*\) \([^ ]*\)/\2 \1/" | awk "{ printf \"%+6s %-35s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s\n\", \$1, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9, \$10, \$11, \$12, \$13, \$14, \$15, \$16, \$17, \$18, \$19, \$20 }" | sed -e "s/\ *$//" | sort | uniq -c | sort -n | tee /tmp/test-results/ModSecurity-ZAP-api-scan.log || \
-              if [ $? -eq 1 ]; then echo "Empty or not existing ModSecurity log from ZAP API scan"; exit 1; else exit 0; fi;
-          # we always want to see this step:        
-          when: always
+#      - run:
+#          name: Show ModSecurity logs of ZAP API Scan
+#          command: |
+#              docker exec apachecrsapi cat /etc/httpd/logs/error.log | grep -o -E " (at|against) .*\[file.*\[id \"[0-9]+.*\[msg \"[^\"]+" | tr -d \" | sed -e "s/ at the end of input at/ at/" -e "s/ required. /. /" -e "s/\[rev .*\[msg/[msg/" -e "s/\. / /" -e "s/(Total .*/(Total ...) .../" | tr -d \] | cut -d\  -f3,9,11- | sed -e "s/^\([^ ]*\) \([^ ]*\)/\2 \1/" | awk "{ printf \"%+6s %-35s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s\n\", \$1, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9, \$10, \$11, \$12, \$13, \$14, \$15, \$16, \$17, \$18, \$19, \$20 }" | sed -e "s/\ *$//" | sort | uniq -c | sort -n | tee /tmp/test-results/ModSecurity-ZAP-api-scan.log || \
+#              if [ $? -eq 1 ]; then echo "Empty or not existing ModSecurity log from ZAP API scan"; exit 1; else exit 0; fi;
+#          # we always want to see this step:        
+#          when: always
 
 #      - run:
 #          name: Show ModSecurity logs of ZAP Active Scan
