tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -218,7 +218,7 @@ jobs:
           # Fail if ModSecurity log is not empty
           name: Show ModSecurity logs of Testcafe Tests
           command: |
-              docker exec apachecrs cat /etc/httpd/logs/error.log | grep ModSecurity | grep msg | tee /tmp/test-results/ModSecurity-Testcafe.log || \
+              docker exec apachecrs cat /etc/httpd/logs/error.log | grep ModSecurity | grep msg | tee /tmp/test-results/ModSecurity-Testcafe.log && \
               if [ $? -eq 0 ]; then echo "Application tests matched one or multiple ModSecurity rules!"; exit 1; else exit 0; fi;
               # If not empty -> Repair your application OR
               #              -> ModSecurity Tuning:
@@ -230,8 +230,8 @@ jobs:
       - run:
           name: Show ModSecurity logs of ZAP API Scan
           command: |
-              docker exec apachecrsapi cat /etc/httpd/logs/error.log 
-              #              if [ $? -eq 1 ]; then echo "Empty or not existing ModSecurity log from ZAP API scan"; exit 1; else exit 0; fi;
+              docker exec apachecrsapi cat /etc/httpd/logs/error.log | grep -o -E " (at|against) .*\[file.*\[id \"[0-9]+.*\[msg \"[^\"]+" | tr -d \" | sed -e "s/ at the end of input at/ at/" -e "s/ required. /. /" -e "s/\[rev .*\[msg/[msg/" -e "s/\. / /" -e "s/(Total .*/(Total ...) .../" | tr -d \] | cut -d\  -f3,9,11- | sed -e "s/^\([^ ]*\) \([^ ]*\)/\2 \1/" | awk "{ printf \"%+6s %-35s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s\n\", \$1, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9, \$10, \$11, \$12, \$13, \$14, \$15, \$16, \$17, \$18, \$19, \$20 }" | sed -e "s/\ *$//" | sort | uniq -c | sort -n | tee /tmp/test-results/ModSecurity-ZAP-api-scan.log || \
+              if [ $? -eq 1 ]; then echo "Empty or not existing ModSecurity log from ZAP API scan"; exit 1; else exit 0; fi;
           # we always want to see this step:        
           when: always
 
