modsecurity logs output

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -36,40 +36,40 @@ jobs:
              docker pull franbuehler/modsecurity-crs && \
              docker run -dt --name apache-crs franbuehler/modsecurity-crs
 
-      - run:
-          name: ZAP baseline test of application
-          # Only fail on error code 1, which indicates at least one FAIL was found.
-          # error codes 2 & 3 indicate WARN or other, and should not break the run
-             #               -u https://raw.githubusercontent.com/${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
-          command: |
-             (
-             docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
-             docker pull owasp/zap2docker-weekly && \
-             docker run -t owasp/zap2docker-weekly zap-baseline.py \
-                -u https://raw.githubusercontent.com/franbuehler/pixi-crs/master/zap-baseline.conf?token=AQ6RVWcCWhass2qYuq5piNkgqnPrHe44ks5abPQLwA \
-                -t http://172.17.0.1:8000/ || \
-              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-             # docker pull ictu/zap2docker-weekly && \
-             # docker run -t ictu/zap2docker-weekly baseline.py \
-             #    -u https://raw.githubusercontent.com/franbuehler/pixi-crs/master/zap-baseline.conf?token=AQ6RVcLZSbEfwBTEEYEgpmtKc6x3CDtMks5aY0pXwA --active_scan \
-             #    -t http://172.17.0.1:8000/ || \
-             #  if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-              )
+#      - run:
+#          name: ZAP baseline test of application
+#          # Only fail on error code 1, which indicates at least one FAIL was found.
+#          # error codes 2 & 3 indicate WARN or other, and should not break the run
+#             #               -u https://raw.githubusercontent.com/${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
+#          command: |
+#             (
+#             docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
+#             docker pull owasp/zap2docker-weekly && \
+#             docker run -t owasp/zap2docker-weekly zap-baseline.py \
+#                -u https://raw.githubusercontent.com/franbuehler/pixi-crs/master/zap-baseline.conf?token=AQ6RVWcCWhass2qYuq5piNkgqnPrHe44ks5abPQLwA \
+#                -t http://172.17.0.1:8000/ || \
+#              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+#             # docker pull ictu/zap2docker-weekly && \
+#             # docker run -t ictu/zap2docker-weekly baseline.py \
+#             #    -u https://raw.githubusercontent.com/franbuehler/pixi-crs/master/zap-baseline.conf?token=AQ6RVcLZSbEfwBTEEYEgpmtKc6x3CDtMks5aY0pXwA --active_scan \
+#             #    -t http://172.17.0.1:8000/ || \
+#             #  if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+#              )
 
-      - run:
-          name: ZAP baseline test of application with CRS
-          # Only fail on error code 1, which indicates at least one FAIL was found.
-          # error codes 2 & 3 indicate WARN or other, and should not break the run
-             #               -u https://raw.githubusercontent.com/${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
-          command: |
-             (
-             docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
-             docker pull owasp/zap2docker-weekly && \
-             docker run -t owasp/zap2docker-weekly zap-baseline.py \
-                -u https://raw.githubusercontent.com/franbuehler/pixi-crs/master/zap-baseline.conf?token=AQ6RVWcCWhass2qYuq5piNkgqnPrHe44ks5abPQLwA \
-                -t http://172.17.0.2:8001/ || \
-              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-              )
+#      - run:
+#          name: ZAP baseline test of application with CRS
+#          # Only fail on error code 1, which indicates at least one FAIL was found.
+#          # error codes 2 & 3 indicate WARN or other, and should not break the run
+#             #               -u https://raw.githubusercontent.com/${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
+#          command: |
+#             (
+#             docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
+#             docker pull owasp/zap2docker-weekly && \
+#             docker run -t owasp/zap2docker-weekly zap-baseline.py \
+#                -u https://raw.githubusercontent.com/franbuehler/pixi-crs/master/zap-baseline.conf?token=AQ6RVWcCWhass2qYuq5piNkgqnPrHe44ks5abPQLwA \
+#                -t http://172.17.0.2:8001/ || \
+#              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+#              )
 
       - run:
           name: ZAP API scan of application
